name: build-docker-container
run-name: ${{ github.actor}}-build-docker-container-${{ github.run_number }}
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - run: echo "just echoing not building"

